oracle.datasource.driver-class-name=oracle.jdbc.OracleDriver
oracle.datasource.jdbc-url=jdbc:oracle:thin:@nun.cc.andrews.edu:1521:DEVL
oracle.datasource.username=vaultappuser
oracle.datasource.password=os89834gi2gduwifghfg


spring.datasource.jdbc-url=jdbc:mysql://143.207.1.39:3306/vaulttest?zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDateTimeCode=false&serverTimezone=America/Detroit
spring.datasource.username=vaulttestuser
spring.datasource.password=!TestingPhobias
spring.servlet.multipart.max-file-size=10MB
vault.api.base-url=https://vaulttest.andrews.edu/vault/ws/publicsafety/ticketing
spring.security.user.name=admin
spring.security.user.password=au_safety_2026