spring.profiles.active=prod
app.description=Andrews University ITS Citation App

spring.datasource.banner.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.banner.url=jdbc:oracle:thin:@nun.cc.andrews.edu:1521:PROD
spring.datasource.banner.username=vlt_dorm_check
spring.datasource.banner.password=39f45qii3UwLwfbFadvY

spring.datasource.url=jdbc:mysql://143.207.1.39:3306/vaulttest?zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDateTimeCode=false&serverTimezone=America/Detroit
spring.datasource.username=vaulttestuser
spring.datasource.password=!TestingPhobias
spring.servlet.multipart.max-file-size=10MB
vault.api.base-url=https://vaulttest.andrews.edu/vault/ws/publicsafety/ticketing
spring.security.user.name=admin
spring.security.user.password=au_safety_2026